/****************************************************************************
**
** Metadata for ransacDLL generated by dumpcpp v6.1.2 using
** dumpcpp ransacDLL.tlb
** from the type library ransacDLL.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_RANSACDLL_NOINLINES
#include "ransacdll.h"
#include <OAIdl.h>

/****************************************************************************
** Meta object code from reading C++ file 'ransac_tnpdwR.h'
**
** Created by: The Qt Meta Object Compiler version 68 (Qt 6.1.2)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include <memory>
#include <QtCore/qbytearray.h>
#include <QtCore/qmetatype.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'ransac_tnpdwR.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 68
#error "This file was generated using the moc from 6.1.2. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

QT_BEGIN_MOC_NAMESPACE
QT_WARNING_PUSH
QT_WARNING_DISABLE_DEPRECATED
struct qt_meta_stringdata_ransacDLL__RANSAC_t {
    const uint offsetsAndSize[16];
    char stringdata0[78];
};
#define QT_MOC_LITERAL(ofs, len) \
    uint(offsetof(qt_meta_stringdata_ransacDLL__RANSAC_t, stringdata0) + ofs), len 
static const qt_meta_stringdata_ransacDLL__RANSAC_t qt_meta_stringdata_ransacDLL__RANSAC = {
    {
QT_MOC_LITERAL(0, 17), // "ransacDLL::RANSAC"
QT_MOC_LITERAL(18, 6), // "Equals"
QT_MOC_LITERAL(25, 0), // ""
QT_MOC_LITERAL(26, 11), // "GetHashCode"
QT_MOC_LITERAL(38, 7), // "GetType"
QT_MOC_LITERAL(46, 16), // "mscorlib::_Type*"
QT_MOC_LITERAL(63, 5), // "Start"
QT_MOC_LITERAL(69, 8) // "ToString"

    },
    "ransacDLL::RANSAC\0Equals\0\0GetHashCode\0"
    "GetType\0mscorlib::_Type*\0Start\0ToString"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_ransacDLL__RANSAC[] = {

 // content:
       9,       // revision
       0,       // classname
       0,    0, // classinfo
       4,   14, // methods
       1,   58, // properties
       0,    0, // enums/sets
       0,    0, // constructors
       0,       // flags
       0,       // signalCount

 // slots: name, argc, parameters, tag, flags, initial metatype offsets
       1,    1,   38,    2, 0x0a,    1 /* Public */,
       3,    0,   41,    2, 0x0a,    3 /* Public */,
       4,    0,   42,    2, 0x0a,    4 /* Public */,
       6,    7,   43,    2, 0x0a,    5 /* Public */,

 // slots: parameters
    QMetaType::Bool, QMetaType::QVariant,    2,
    QMetaType::Int,
    0x80000000 | 5,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int,    2,    2,    2,    2,    2,    2,    2,

 // properties: name, type, flags
       7, QMetaType::QString, 0x00005001, uint(-1), 0,

       0        // eod
};



const QMetaObject ransacDLL::RANSAC::staticMetaObject = { {
    QMetaObject::SuperData::link<QAxBaseObject::staticMetaObject>(),
    qt_meta_stringdata_ransacDLL__RANSAC.offsetsAndSize,
    qt_meta_data_ransacDLL__RANSAC,
    nullptr,
    nullptr,
qt_incomplete_metaTypeArray<qt_meta_stringdata_ransacDLL__RANSAC_t
, QtPrivate::TypeAndForceComplete<QString, std::true_type>
, QtPrivate::TypeAndForceComplete<bool, std::false_type>, QtPrivate::TypeAndForceComplete<QVariant, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<mscorlib::_Type *, std::false_type>, QtPrivate::TypeAndForceComplete<QString, std::false_type>, QtPrivate::TypeAndForceComplete<QString, std::false_type>, QtPrivate::TypeAndForceComplete<QString, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>


>,
    nullptr
} };




void *ransacDLL::RANSAC::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, qt_meta_stringdata_ransacDLL__RANSAC.stringdata0))
        return static_cast<void*>(this);
    return QAxBaseObject::qt_metacast(_clname);
}


QT_WARNING_POP
QT_END_MOC_NAMESPACE


ransacDLL::RANSAC::RANSAC(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{3d788165-8436-4bb9-882b-b03c859f9ee3}"));
}

/****************************************************************************
** Meta object code from reading C++ file '_ransac_BNSYvm.h'
**
** Created by: The Qt Meta Object Compiler version 68 (Qt 6.1.2)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include <memory>
#include <QtCore/qbytearray.h>
#include <QtCore/qmetatype.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file '_ransac_BNSYvm.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 68
#error "This file was generated using the moc from 6.1.2. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

QT_BEGIN_MOC_NAMESPACE
QT_WARNING_PUSH
QT_WARNING_DISABLE_DEPRECATED
struct qt_meta_stringdata_ransacDLL___RANSAC_t {
    const uint offsetsAndSize[16];
    char stringdata0[79];
};
#define QT_MOC_LITERAL(ofs, len) \
    uint(offsetof(qt_meta_stringdata_ransacDLL___RANSAC_t, stringdata0) + ofs), len 
static const qt_meta_stringdata_ransacDLL___RANSAC_t qt_meta_stringdata_ransacDLL___RANSAC = {
    {
QT_MOC_LITERAL(0, 18), // "ransacDLL::_RANSAC"
QT_MOC_LITERAL(19, 6), // "Equals"
QT_MOC_LITERAL(26, 0), // ""
QT_MOC_LITERAL(27, 11), // "GetHashCode"
QT_MOC_LITERAL(39, 7), // "GetType"
QT_MOC_LITERAL(47, 16), // "mscorlib::_Type*"
QT_MOC_LITERAL(64, 5), // "Start"
QT_MOC_LITERAL(70, 8) // "ToString"

    },
    "ransacDLL::_RANSAC\0Equals\0\0GetHashCode\0"
    "GetType\0mscorlib::_Type*\0Start\0ToString"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_ransacDLL___RANSAC[] = {

 // content:
       9,       // revision
       0,       // classname
       0,    0, // classinfo
       4,   14, // methods
       1,   58, // properties
       0,    0, // enums/sets
       0,    0, // constructors
       0,       // flags
       0,       // signalCount

 // slots: name, argc, parameters, tag, flags, initial metatype offsets
       1,    1,   38,    2, 0x0a,    1 /* Public */,
       3,    0,   41,    2, 0x0a,    3 /* Public */,
       4,    0,   42,    2, 0x0a,    4 /* Public */,
       6,    7,   43,    2, 0x0a,    5 /* Public */,

 // slots: parameters
    QMetaType::Bool, QMetaType::QVariant,    2,
    QMetaType::Int,
    0x80000000 | 5,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int,    2,    2,    2,    2,    2,    2,    2,

 // properties: name, type, flags
       7, QMetaType::QString, 0x00005001, uint(-1), 0,

       0        // eod
};



const QMetaObject ransacDLL::_RANSAC::staticMetaObject = { {
    QMetaObject::SuperData::link<QAxBaseObject::staticMetaObject>(),
    qt_meta_stringdata_ransacDLL___RANSAC.offsetsAndSize,
    qt_meta_data_ransacDLL___RANSAC,
    nullptr,
    nullptr,
qt_incomplete_metaTypeArray<qt_meta_stringdata_ransacDLL___RANSAC_t
, QtPrivate::TypeAndForceComplete<QString, std::true_type>
, QtPrivate::TypeAndForceComplete<bool, std::false_type>, QtPrivate::TypeAndForceComplete<QVariant, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<mscorlib::_Type *, std::false_type>, QtPrivate::TypeAndForceComplete<QString, std::false_type>, QtPrivate::TypeAndForceComplete<QString, std::false_type>, QtPrivate::TypeAndForceComplete<QString, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>, QtPrivate::TypeAndForceComplete<int, std::false_type>


>,
    nullptr
} };




void *ransacDLL::_RANSAC::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, qt_meta_stringdata_ransacDLL___RANSAC.stringdata0))
        return static_cast<void*>(this);
    return QAxBaseObject::qt_metacast(_clname);
}


QT_WARNING_POP
QT_END_MOC_NAMESPACE


ransacDLL::_RANSAC::_RANSAC(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}


